### ISSUE TITLE
Confirm productvariant Configuration

### ISSUE THREAD

**Issue by aikchun** [simkimsia/label-ecommerce#10]
@daphneling Please confirm the product variants and their names.

Note:  Split English/Chinese Name Pack (Iron On Labels) doesn't have variants indicate while the Sticker version has. (Hightlighted in red)
![productvariantss](https://f.cloud.github.com/assets/4145525/719705/80b8cf08-df94-11e2-9b28-8f1f9c6f484c.png)

@simkimsia

**Comment by daphneling** [comment]
Hi Aik Chun,

Variants are correct. For the split pack (iron ons), no need for variants.

Sorry, some changes to the prices. All standard packs are $15, split packs
(both stickers and iron ons) are $15, Get Me Started is $30, Give me
Everything is $50.

On Fri, Jun 28, 2013 at 9:46 AM, Aik Chun notifications@github.com wrote:

> @daphneling https://github.com/daphneling Please confirm the product
> variants and their names.
> 
> Note: Split English/Chinese Name Pack (Iron On Labels) doesn't have
> variants indicate while the Sticker version has. (Hightlighted in red)
> [image: productvariantss]https://f.cloud.github.com/assets/4145525/719705/80b8cf08-df94-11e2-9b28-8f1f9c6f484c.png
> 
> @simkimsia https://github.com/simkimsia
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simkimsia/label-ecommerce/issues/10
> .

## 

www.motherinc.org

**Comment by aikchun** [comment]
@daphneling 

So do we need to have color variants?

Cause the design included this.

![ss](https://f.cloud.github.com/assets/4145525/721608/37bbe156-dfe8-11e2-95f2-49742ce85e10.png)

**Comment by simkimsia** [comment]
@AikChun all products with more than 1 variants create variants

those with no variants create DEFAULT variant in database.

export database.

then close this issue.

**Comment by daphneling** [comment]
we have the same color variants for all the products. currently we have 11 color variants (available here - https://www.facebook.com/media/set/?set=a.232376093439193.73146.193502597326543&type=1)

How should we send over the visuals for each variant? in jpeg format ok? any specific dimensions?
