### ISSUE TITLE
Add padding (space below the text and above footer). Space looks a bit tight. 

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#102]
WE don't know what you mean. Can append with some screenshots?

**Comment by daphneling** [comment]
![screen shot 2013-12-06 at 11 23 51 am](https://f.cloud.github.com/assets/4834792/1689588/b1141624-5e26-11e3-9741-4a82b4461fd7.png)

**Comment by daphneling** [comment]
the space above the white box can make a bit bigger

**Comment by simkimsia** [comment]
@AikChun Fix this.
