### ISSUE TITLE
images on the Shop pages don't load for me

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#103]
A lot of images on the Shop pages don't load for me, even after I've refreshed several times at different intervals. Some of the images on the "choose a design" also not loading.

**Comment by simkimsia** [comment]
ref https://github.com/simkimsia/label-ecommerce/commit/d023fe2daeda566c156af0049c39f3db15d97f0b

**Comment by simkimsia** [comment]
at daphne, we have checked against this http://test.childlabel.com/products/summary Please give me the last image for the product at the bottom for chinese name iron on

**Comment by daphneling** [comment]
Would it be easier if we uploaded the images on our end? What are the dimensions for the boxes? We need to resize all the images because some of them look out of proportion

**Comment by simkimsia** [comment]
@daphneling Ahhhh I see the issue now.

The problem is we are using the same image for 

http://test.childlabel.com/products/view/1

and 

http://test.childlabel.com/products/summary

http://test.childlabel.com/products/summary is using 250 x 250
http://test.childlabel.com/products/view/1 is using 870 x 628

The easiest way out is you create the image as 628 x 628 and then upload via
1. Go to Products
2. Select the desired Product >> Image
