### ISSUE TITLE
Replace "choose a design" image with revised bigger one. 

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#104]
Is this inside the dropbox shared folder?

**Comment by daphneling** [comment]
do you have the dropbox labeled stuff? i just dropped it there

**Comment by simkimsia** [comment]
I have the dropbox.

What is the path to the image?

This is what I see.

![screen shot 2013-12-06 at 11 55 42 am](https://f.cloud.github.com/assets/245021/1689688/59552898-5e2a-11e3-80fc-ce289e243ec7.png)

**Comment by daphneling** [comment]
ok done its in the main folder

**Comment by simkimsia** [comment]
@daphneling Sorry I have refreshed my dropbox. Still don't see it.

**Comment by daphneling** [comment]
i've attached it here as well.

On Fri, Dec 6, 2013 at 12:12 PM, simkimsia notifications@github.com wrote:

> @daphneling https://github.com/daphneling Sorry I have refreshed my
> dropbox. Still don't see it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simkimsia/label-ecommerce/issues/104#issuecomment-29962451
> .

## 

www.motherinc.org

**Comment by simkimsia** [comment]
I don't see the attachment or any changes in the dropbox. Can you update it here in the GitHub issue tracker?

**Comment by daphneling** [comment]
it says they don't support the file type its a psd file. Can i give it to you as a jpg or gif?

**Comment by daphneling** [comment]
![tab](https://f.cloud.github.com/assets/4834792/1691746/9ba58286-5e68-11e3-8b08-c1a480f24dda.gif)

**Comment by daphneling** [comment]
![tab](https://f.cloud.github.com/assets/4834792/1691748/b3c39628-5e68-11e3-8f8f-b74d58c284d9.jpg)

**Comment by daphneling** [comment]
ok i uploaded both the gif and jpeg. if u need the psd file let me know

**Comment by daphneling** [comment]
thanks. possible to shift it to the right a bit so it's flushed right with the contact button above it. 
![screen shot 2013-12-27 at 10 42 43 am](https://f.cloud.github.com/assets/4834792/1812997/a9669bba-6ea0-11e3-8556-a9222a70a8d5.png)

**Comment by simkimsia** [comment]
@daphneling  please check this issue again http://test.childlabel.com/products/view/2

if okay, feel free to close & comment it

**Comment by daphneling** [comment]
brilliant, thanks!

**Comment by simkimsia** [comment]
closed with https://github.com/simkimsia/label-ecommerce/commit/e94defc6b11109b45ec4d2b71c7910254d653163
