### ISSUE TITLE
Swapping out images from the rotating image gallery box

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#106]

**Comment by simkimsia** [comment]
Do it like this:
1. Do X
2. Do Y
3. Verb Noun

**Comment by aikchun** [comment]
1. go to Admin Product page and select 'edit'.

![step1](https://f.cloud.github.com/assets/4145525/1689516/df2eba66-5e24-11e3-94f1-50f532b7f7a1.png)
1. Select `Show its Variants`

![step2](https://f.cloud.github.com/assets/4145525/1689518/ea9e39a8-5e24-11e3-8197-94a3ae5500a7.png)
1. Select the `images` on the desired variant

![step3](https://f.cloud.github.com/assets/4145525/1689522/0e598e7e-5e25-11e3-882b-a06da4435f22.png)
1. Delete/add images as desired to be displayed on the rotating gallery

![step4](https://f.cloud.github.com/assets/4145525/1689528/233c5cd6-5e25-11e3-8927-efb55d434985.png)

**Comment by daphneling** [comment]
got it thanks

**Comment by simkimsia** [comment]
issue closed

**Comment by daphneling** [comment]
Sorry i tried to click on the image to change but it doesn't work. As in nothing happens when I try to change the images following the same steps. Or when I click show its variants, nothing happens either
