### ISSUE TITLE
Swapping out images for the 3 images in boxes below the rotating image gallery - can we link them to different products on the Shop page?

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#107]

**Comment by aikchun** [comment]
Do you mean that we take out this image to replace with 3 other images that links to other products such as 'Birthday Labels', 'Chinese Labels' and 'Book Labels'?

![doyoumean](https://f.cloud.github.com/assets/4145525/1689585/705640f8-5e26-11e3-8929-43315852889e.png)

**Comment by daphneling** [comment]
We'll be creating new images for this. Can we upload this on our end as well?

**Comment by simkimsia** [comment]
@daphneling Yes. Please see: https://github.com/simkimsia/label-ecommerce/issues/103#issuecomment-29961694
