### ISSUE TITLE
Under the individual products, include text box for customers to fill in the names

### ISSUE THREAD

**Issue by daphneling** [simkimsia/label-ecommerce#12]
After they select the product ==> select the variant (if any) ==> select color variant ==> include 5 options to select fonts ==> include text box to type in their name (include 2 lines - and chinese text compatible as well)

*refer to sample image below. For the font selection, it can be a drop down menu or 5 different boxes and they click the font they want. And for the name, instead of "first name" and "last name", use "Name (1st line)" and "Name (2nd line)". 

For now, we'll launch without the preview function, so after they type in the name, they can proceed to checkout and payment. 

![screen shot 2013-07-02 at 12 00 42 am](https://f.cloud.github.com/assets/4834792/731273/adc17696-e267-11e2-9684-6812acef2ba7.png)

**Comment by simkimsia** [comment]
@daphneling I did not see this in the html files sent to us.

Can give us the html and css code for this?

**Comment by simkimsia** [comment]
this is closed with changes happening in #73
