### ISSUE TITLE
uploaded image should display on the product view page

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#20]

**Comment by simkimsia** [comment]
do this when #16 and #17 are completed

**Comment by simkimsia** [comment]
@AikChun  in anticpation of meeting on 11th at 8am.

1) have a function in Product that will prepare the viewvars in advance for the ProductsController->view action

``` php
/**
 * 
 * @param $options Array of options. 
 *
 * Retrieve the data for /products/view the code may be incomplete
 */
    public function getViewVars($id, $options = array()) {
// the fields you want from Product...
        $fields = array(
            'Product.id', 
            'Product.description', 
            'Product.title', 
        );
        $conditions = array('Product.id' => $id);
        $product = $this->find('first', array(
            'conditions' => $conditions,
            'fields' => $fields
        ));
// get variants and their images
        $variantsAndImages = $this->getVariantsAndImages($id);
        $variantsAndImages = Hash::extract($variantsAndImages, '{n}.Variant');
        $product['variants'] = $variantsAndImages;
        return $product;
    }

```

2) have another function that will get simply the variant and images based on product id

``` php
/**
 * 
 * Retrieve the variants and images
 */
    public function getVariantsAndImages($id = null) {
        $conditions = array(
            'ProductVariant.product_id' => $id,
        );
        $fields = array(
            'ProductVariant.id', 'ProductVariant.product_id', 
// and many more where necessary
        );
        $variants = $this->ProductVariant->find('all', array(
            'conditions' => $conditions,
            'fields' => $fields,
          'contain' => array('ProductImage') // go google at cakephp for containable to get better idea
        ));
        return $variants;
    }

```

3) use this->log to test these functions work as expected.

4) at the ProductsController action `view` call getViewVars() to get the data needed.

5) edit the View/Products/view.ctp to display the images accordingly

**Comment by simkimsia** [comment]
6) if variants only 1 then dont display list of names else display.

7) show the images with the ones i emailed you

**Comment by aikchun** [comment]
Currently, the product images are added on the view page statically. Therefore, the only 3 images are able to be placed on the page.

**Comment by aikchun** [comment]
This is currently how the product view page looks like: 
![products_view_preview](https://f.cloud.github.com/assets/4145525/792901/2f0e548e-ebce-11e2-9451-1fce3bb0743b.png)

**Comment by simkimsia** [comment]
@AikChun  

okay go and measure the ratio of the **original images** you upload.

Basically width in pixels / height in pixels

State here and include the original width and height.

**Comment by simkimsia** [comment]
@simkimsia will implement jquery for the rotation

**Comment by simkimsia** [comment]
closed
