### ISSUE TITLE
add ordering function to images

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#22]

**Comment by aikchun** [comment]
The algorithm is implemented on a list of images OF a particular variant OF a particular product. Unless the algorithm is implemented on the index of all images of all variants or all products, even if there's only one image of a variant of a product, I would still be able to move it up if that image's as long as the 'left' element is not 0.

**Comment by simkimsia** [comment]
@AikChun i am not sure what you mean by implementing on the index of all imae of all variants of all products.

The algo works only for images within a particular variant.

**Comment by aikchun** [comment]
@simkimsia So it would mean that the first image of every variant 'left' would be 0?

**Comment by simkimsia** [comment]
@AikChun 
first image of every variant `left` is 0 yes. 
first image of every variant `order` is also 0.
all last images of every variant `right` is 999.

this applies to the variants of a product.
