### ISSUE TITLE
add ordering function for variants

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#23]
implementation similar to #22

**Comment by simkimsia** [comment]
use https://github.com/simkimsia/label-ecommerce/commit/4d9dd5a54c6a750c1435f306fc6a49c64b7e12da as implementation guide.

the steps are (roughly):

add new database columns:order, left, right with the correct default values and datatype
add new action swap_order in controller
add new route for swap_order action
implement the correct redirection for swap_order
add 2 new functions in model getOrderStats and swap
modify the index view so that you can retrieve the left, right for each item
ensure that the action for the index view is displaying based on the order `order`
test the following scenario

assume at least 4 variants scenario:
2nd and 3rd swap by pressing down in 2nd // should work
2nd and 3rd swap by pressing up in 3rd // should work
1st and 2nd swap by pressing up in 2nd // should work
1st and 2nd swap by pressing down in 1st // should work
last and 2nd last swap by pressing up in last // should work
last and 2nd last swap by pressing down in 2nd last // should work

1st press up should display error message
last press down should display error message

**Comment by aikchun** [comment]
Currently there's no index page for variants. the index refers to the list of variants of a particular product. 

In order to make sense of this, I would create a index page containing all variants of ALL products and implement the ordering algorithm there.

**Comment by simkimsia** [comment]
@AikChun There is NO need to have an index page containing all variants of all products. Therefore, there is NO need to have the ordering algorithm there as well.

**Comment by simkimsia** [comment]
If a product has just 1 variant, that 1 variant will have 0 as order, 0 as left and 999 as right.
if a variant has just 1 image, that 1 image will have 0 as order, 0 as left and 999 as right
