### ISSUE TITLE
when add new image, need to reorder

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#24]
ref #22

**Comment by simkimsia** [comment]
need a getAllOrderStats
basically is to retrieve all images and their order stats only

need a getLastOrderStats
basically is to retrieve the last image and its order stats only

need a reorder function 

pseudo code is
1) getAllOrderStats
2) reorder the order number using foreach loop
3) savemany

**Comment by simkimsia** [comment]
need a createAndReorder function

pseudo code is
1) getLastOrderStats
2) create and save the new image. retrieve the id of the new image.
3) now change the currentLast's right to the new image id
4) set the left of new image to currentLast id and the order of new image to (currentLast's order + 1)
5) do a saveMany on currentLast and newLast

**Comment by simkimsia** [comment]
@AikChun  Do this for variant also

**Comment by aikchun** [comment]
@simkimsia This feature had been done for variant.
