### ISSUE TITLE
when delete new image, need to reorder

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#25]
ref #22 

do this only if https://github.com/simkimsia/label-ecommerce/issues/24#issuecomment-21035168 is completed

and we have a getAllOrderStatsExcept function

getAllOrderStatsExcept is similar to getAllOrderStats 

just that we ensure that the excepted item is not going to be selected.

**Comment by simkimsia** [comment]
assuming the reorder function is completed, 
assuming we have a getAllOrderStatsExcept($product_variant_id, $id) function 

we need a deleteAndReorder function

pseudocode is 
1) getOrderStats of the about-to-delete item
2) $theRest = getAllOrderStatsExcept($product_variant_id, $id) where the $id is the about-to-delete item
3) check if its the first one or the last one or neither

4) **Which one are we deleting?**
a) if its the first, change the left of the first in $theRest to 0.
b) if its the last, change the right of the last in $theRest to 999.
c) if its neither, : 
     i) get the $leftOfToBeDeleted and $rightOfToBeDeleted from the $theRest
    ii) change the right of $leftToBeDeleted and the left of $rightOfToBeDeleted accordingly inside $theRest

5) delete the item
6) saveMany($theRest);
7) run reorder();

**Comment by simkimsia** [comment]
@AikChun  Do this for variants also

**Comment by aikchun** [comment]
@simkimsia This feature had been done already.
