### ISSUE TITLE
Footer: Under Value Packs, there should be only 2: Get Me Started Pack and Give Me Everything Pack. The rest can delete. (Same as Nav Menu under Shop

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#3]

**Comment by daphneling** [comment]
Some minor text changes. 

Under Stickers, 
1. Change "Small Rectangle" to "Rectangle Labels"
2. Change "Chinese Name Labels" to "Chinese Labels"
3. Change "Split English/Chinese Name Pack" to "Split English/Chinese Pack"

Under Iron-Ons,
1. Change "Iron-Ons" to "Iron Ons"
2. Change "Small Rectangle" to "Rectangle Labels"
3. Change "Chinese Name Labels" to "Chinese Labels"
4. Change "BSplit English/Chinese Name Pack" to "Split English/Chinese Pack"

Can apply these same category names to the Nav Menu Under Shop

**Comment by simkimsia** [comment]
@daphneling Hi these changes are meant only for the footer yes?

Cause your products currently are named like this by you.

![screen shot 2013-06-28 at 8 29 49 am](https://f.cloud.github.com/assets/245021/719523/0138d93a-df8a-11e2-85fb-e5667972e5f7.png)

**Comment by daphneling** [comment]
Sorry, we had some changes in naming the packs - these apply to the nav
menu at the top too. These names will be consistent throughout the site,
even on the individual product pages

On Fri, Jun 28, 2013 at 8:30 AM, simkimsia notifications@github.com wrote:

> @daphneling https://github.com/daphneling Hi these changes are meant
> only for the footer yes?
> 
> Cause your products currently are named like this by you.
> 
> [Uploading Screen Shot 2013-06-28 at 8.29.49 AM.png . . .]()
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/simkimsia/label-ecommerce/issues/3#issuecomment-20164038
> .

## 

www.motherinc.org

**Comment by simkimsia** [comment]
@AikChun can we close this?

**Comment by aikchun** [comment]
@simkimsia Yes, I'll close this.
