### ISSUE TITLE
create Model and Controller for shipping_options

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#35]
1) backup latest database copy
2) create new table called shipping_options
id int 11 primary 
name varchar 255
period varchar 255
fees decimal 10,2
3) bake the model
4) bake the controller
with admin actions but remove all the non admin actions
5) bake the views for the admin actions

**Comment by simkimsia** [comment]
expected options are:

free shipping via SingPost
registered mail via SingPost $2.24

both are 2 weeks

**Comment by aikchun** [comment]
closed with https://github.com/simkimsia/label-ecommerce/commit/dc7d4a7bc0cff80f75f84e1364b2708869caa732
