### ISSUE TITLE
I've tried the preview - possible to change the font, font size and include spacing on the page?

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#5]

**Comment by simkimsia** [comment]
@daphneling can we clarify if you mean by:

"US" changing the font, font size and spacing? or is it by you?

can include a screenshot to help us better understand this particular preview?

Thank you!

**Comment by daphneling** [comment]
This was in reference to the font used for the product descriptions. Can we use the same font as the footer? For consistency, keep all the fonts to the footer font. The font size and spacing looks great, just change the font will do. 

![screen shot 2013-07-01 at 11 53 59 pm](https://f.cloud.github.com/assets/4834792/731225/98c79816-e266-11e2-9f06-a31f35eabd06.png)

**Comment by simkimsia** [comment]
@AikChun change the font for product description.

Use the same font as the footer.
