### ISSUE TITLE
use alertify to implement this.

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#64]
1. When they add an order to the cart, can we include a pop up message to say "Added to Cart!"
   understood

**Comment by aikchun** [comment]
![alertify-pop-up-message](https://f.cloud.github.com/assets/4145525/1187185/e74aa35a-235e-11e3-871c-7a9d57d44994.png)

This has already been done. It's currently available on the test server as well. @simkimsia @daphneling
