### ISSUE TITLE
need a representative image for each product. this is to be used for product view and summary

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#82]

**Comment by aikchun** [comment]
I suggest we either reduce the font size of the products name on the summary page or change the naming format because the length of some product names are pushing the area of the product out of line.

**Comment by simkimsia** [comment]
Fontsize

**Comment by aikchun** [comment]
ref https://github.com/simkimsia/label-ecommerce/commit/456e6acf708104bb22d7079a7aa28a59eb37839f
added link to upload/replace representative image from admin product index 
added ability to add/replace representive images of product.
added routing specifications.
added to admin_add to show the current representative image of the product.

**Comment by simkimsia** [comment]
a) where teh new database for this?
b) remove teh auth->allow in the beforeFilter

i need you to get to the point where i can add or change the image at the test server.

**Comment by aikchun** [comment]
Able to upload Representative pictures to test server. But the delete function is not completed yet.

**Comment by simkimsia** [comment]
no need for delete.

With gratitude,
KimSia
金城

**Comment by simkimsia** [comment]
closed with https://github.com/simkimsia/label-ecommerce/commit/17e35286ebeda92fadce7ed44e1204e1908c61c7
