### ISSUE TITLE
Test register at cart step 2 for duplicate email

### ISSUE THREAD

**Issue by simkimsia** [simkimsia/label-ecommerce#85]
No code required just test and write the results here.

Try to register a user that the email is already used. Make sure things like password match confirm password and full name and short name are non empty.

State what happens here.

**Comment by aikchun** [comment]
![duplicate_user_registration](https://f.cloud.github.com/assets/4145525/1216545/7410040c-268d-11e3-8333-24c914cf3901.png)

This shows up as there's a duplicate entry in the database.

No emails were sent.

**Comment by simkimsia** [comment]
@AikChun 

i fixed teh above with https://github.com/simkimsia/label-ecommerce/commit/7b69fcb9953edf36ed030caba21221149bfab327

now test the following:
1. register with non matching passwords and non-existent email
   -  expected behavior see error message about non matching passwords and email is sticky
2. register with matching passwords and existent email and password is the correct password
   -  expected login as per normal and go to cart step 3. no new user is created.
3. register with matching passwords and existent email but password is not correct
   -  expected behavior see error message about duplicate email and email is sticky
4. register with matching passwords and non-existent email
   -  expected behavior create new user and send email to user and user proceeds to step 3
5. register with non-matching passwords and existent email
   -  expected behavior 2 error messages: 1 about passowrds not match and 1 about duplicate email. email is sticky.

reply to each scenario to tell me what works and what does not.

**Comment by aikchun** [comment]
Sticky is unable to work with in all scenarios. The sticky data is written only when the $this->User->create() fails. $this->user->create() would only fail when the user tries to sign in with existing email in the database, which has already been catered for in determining $registerUser therefore it will never trigger.

I have fixed the sticky problem with this commit https://github.com/simkimsia/label-ecommerce/commit/ba71ba73c596b0fe715d72d6b8ba67c86171e43b

And also added sticky removal upon, logging through the registration form.

After the changes made.. all the scenarios work as expected.
